### ISSUE TITLE
Toggling selection tool cause an error

### ISSUE THREAD

**Issue by Samweli** [planetlabs/qgis-planet-plugin#120]
Clicking the selection tool for first time without any active layer result into plugin error.

This is caused by access of uninitialized variable here https://github.com/planetlabs/qgis-planet-plugin/blob/9217a94737b0e0d063151ffdde2f819c5216921d/planet_explorer/gui/pe_filters.py#L737

cc @Jeremy-Prior @vermeulendivan 

Screenshot of the error
![issue_toggling_selection](https://user-images.githubusercontent.com/2663775/217810765-e7d52e86-1894-47a1-a266-4e2aca32b69e.gif)

**Comment by vermeulendivan** [comment]
@Samweli Hey. Thanks for showing this. It happens with me even if a layer is active. The function here     [def _toggle_selection_tools(self):](https://github.com/planetlabs/qgis-planet-plugin/blob/9217a94737b0e0d063151ffdde2f819c5216921d/planet_explorer/gui/pe_filters.py#L723) - the _toggle_selection_tools is no longer required because of changes. This issue does not happen if you click on the drop down arrow, likely why it went unnoticed. Will have the fix ready shortly.

**Comment by Samweli** [comment]
> @Samweli Hey. Thanks for showing this. It happens with me even if a layer is active. The function here [def _toggle_selection_tools(self):](https://github.com/planetlabs/qgis-planet-plugin/blob/9217a94737b0e0d063151ffdde2f819c5216921d/planet_explorer/gui/pe_filters.py#L723) - the _toggle_selection_tools is no longer required because of changes. This issue does not happen if you click on the drop down arrow, likely why it went unnoticed. Will have the fix ready shortly.

@vermeulendivan alright, thanks in advance for the fix.

**Comment by vermeulendivan** [comment]
@Samweli Issue has been fixed. Here is the PR: https://github.com/planetlabs/qgis-planet-plugin/pull/122

[Screencast from 09-02-2023 15:12:48.webm](https://user-images.githubusercontent.com/79740955/217823865-939709d9-c395-46b6-b9a1-40df6ae8ade5.webm)
